create user struts IDENTIFIED BY struts;

grant dba TO struts;

CREATE TABLE "STRUTS"."USUARIOS"(	
"USUARIO" VARCHAR2(10 BYTE), 
"PASSWORD" VARCHAR2(10 BYTE), 
"NOMBRE" VARCHAR2(200 BYTE), 
"APELLIDOS" VARCHAR2(200 BYTE), 
"TELEFONO" NUMBER(9,0), 
"FECHA_NACIMIENTO" DATE, 
"SUELDO" NUMBER(7,0), 
"NUM_HIJOS" NUMBER(3,0));

Insert into STRUTS.USUARIOS (USUARIO,PASSWORD,NOMBRE,APELLIDOS,TELEFONO,FECHA_NACIMIENTO,SUELDO,NUM_HIJOS) values ('pepe','pepe',null,null,null,null,null,null);
Insert into STRUTS.USUARIOS (USUARIO,PASSWORD,NOMBRE,APELLIDOS,TELEFONO,FECHA_NACIMIENTO,SUELDO,NUM_HIJOS) values ('jose','jose',null,null,null,null,null,null);
Insert into STRUTS.USUARIOS (USUARIO,PASSWORD,NOMBRE,APELLIDOS,TELEFONO,FECHA_NACIMIENTO,SUELDO,NUM_HIJOS) values ('pedro','pedro',null,null,null,null,null,null);;